### PR TITLE
Restore correct CGA compatible mode behavior in (S)VGA.

### LINKED ISSUE #3942: VGA and SVGA backwards compatibility with CGA is broken
### What happened?

Graphics are distorted when I run CGA graphics using any graphics adapter that should be backwards compatible. This issue does not exist on older builds, such as 5111

### Configuration file

```ini
[General]
vid_renderer = qt_software
force_43 = 1
vid_resize = 2
window_fixed_res = 1200x900
video_fullscreen_first = 0
mouse_sensitivity = 0.1

[Machine]
machine = 486vipio2
cpu_family = i486dx2_pc330
cpu_speed = 66666666
cpu_multi = 2
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
mem_size = 32768

[Video]
gfxcard = ega

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = sb16
midi_device = fluidsynth

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load
scsicard_1 = ncr53c875

[NCR 53c875 #1]
bios = 1

[Matrox Mystique]
memory = 4

[Standard PS/2 Mouse]
buttons = 2

[Hard disks]
hdd_01_parameters = 17, 15, 1224, 0, ide
hdd_01_fn = D:/Games/x86Box/x86drive2.vhd
hdd_01_speed = 1992_3600rpm
hdd_02_parameters = 63, 16, 4161, 0, scsi
hdd_02_scsi_location = 0:00
hdd_02_fn = D:/Games/x86Box/x86scsi2.vhd
hdd_02_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd
cdrom_01_speed = 24
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
fdd_01_image_history_01 = D:/Games/x86Box/Floppy/bootme.img
cdrom_01_host_drive = 200
cdrom_01_image_path = D:/Games/x86Box/CDROM/DN3D_REG.iso
cdrom_01_type = 86BOX_CD-ROM_1.00

[Sound Blaster 16 PnP]
control_pc_speaker = 0
receive_input = 0
receive_input401 = 1

[FluidSynth]
sound_font = D:/Games/x86Box/roms/SC-55.SoundFont.v1.2b.sf2
output_gain = 100
chorus = 1
chorus_voices = 3
chorus_level = 20
chorus_speed = 30
chorus_depth = 80
chorus_waveform = 0
reverb = 1
reverb_room_size = 20
reverb_damping = 0
reverb_width = 5
reverb_level = 90
interpolation = 2

[Sound Blaster 16]
base = 0220
base401 = 0330
irq = 5
dma = 1
dma16 = 5
opl = 1
control_pc_speaker = 0
receive_input = 0
receive_input401 = 1

[Matrox Mystique 220]
memory = 4

[Matrox Millennium]
memory = 4

[S3 ViRGE/GX2 (Diamond Stealth 3D 4000) AGP]
bilinear = 0
dithering = 1

[3dfx Voodoo Banshee]
memory = 8
bilinear = 0
dithersub = 1
dacfilter = 0
render_threads = 4
recompiler = 1

[S3 ViRGE/GX2 (Diamond Stealth 3D 4000) PCI]
bilinear = 0
dithering = 1

[S3 Vision864 PCI (Paradise Bahamas 64)]
memory = 2

[CGA]
display_type = 0
composite_type = 1
rgb_type = 0
snow_enabled = 0

[SuperEGA]
memory = 256
monitor_type = 9

[EGA]
memory = 256
monitor_type = 7
```

### Operating system

Windows 11

### CPU

Intel i3 13100F

### 86Box version

5290

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TC1995**
Summary
=======
See above.

Checklist
=========
* [x] Closes #3942
* [x] I have discussed this with core contributors already
* [ ] This pull request requires changes to the ROM set
  * [ ] I have opened a roms pull request - https://github.com/86Box/roms/pull/changeme/

References
==========
_Provide links to datasheets or other documentation that helped you implement this pull request._

### CODE REVIEW

File: src/video/vid_svga.c [hunk 1]
```diff
@@ -639,27 +639,26 @@ svga_recalctimings(svga_t *svga)
             svga->hdisp *= (svga->seqregs[1] & 8) ? 16 : 8;
             svga->hdisp_old = svga->hdisp;
 
-            if ((svga->bpp <= 8) || ((svga->gdcreg[5] & 0x60) == 0x00)) {
+            if ((svga->bpp <= 8) || ((svga->gdcreg[5] & 0x60) <= 0x20)) {
```
Comment (iamgreaser) [inline src/video/vid_svga.c:642]: This is not a critique of this commit, but a critique of how stuff unfolded in order to support `[INSERT SPECIFIC SVGA ADAPTER HERE]`. All things considered, this pull request does fix the issue.
What's happening here will need to be tidied up at some point, because so far it seems that this was written to fix a specific adapter, but... well, I can tell you right now that the second condition in the OR will break on an S3 Trio when someone decides to get a bit funky (SVGA modes override VGA modes on S3 Trio, though the extent hasn't been fully worked out yet) and actually, maybe someone won't even need to get funky for this to break.
However, fixing this will also require working out which cards this workaround was required for. From what I can tell, this was for the Matrox MGA cards.

Anyway, this should fix the problem, at least for now. But we really do need to track all the differences for the SVGA chipsets we emulate.
