### PR TITLE
qt: Shortcut fixes

### LINKED ISSUE #2626: The CTRL+F11 and CTRL+F12 key combinations do not work in fullscreen mode
**Describe the bug**
Keyboard shortcuts CTRL+F11 (screenshot) and CTRL+F12 (reload) do not work in fullscreen mode. This bug was introduced in build 3501. In build 3495 everything works fine.

**To Reproduce**
1. Start the machine in 86Box.
2. Switch to fullscreen mode.
3. Press CTRL+F11 (screenshot) or CTRL+F12 (reload).
4. See error.

**Expected behavior**
The CTRL+F11 and CTRL+F12 key combinations should work fine in fullscreen mode.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H2
 - 86Box v3.7.1 x64 Build 4060
 - Build type: regular, old recompiler.

### PR DESCRIPTION
**Pull request by Cacodemon345**
Summary
=======
qt: Shortcut fixes

* Make Pause key pause/resume the emulator when both Alts are held, passthrough to emulated machine otherwise.
* Make screenshot taking and C+A+D shortcuts work on fullscreen

Checklist
=========
* [X] Closes #2626
* [ ] I have discussed this with core contributors already
* [ ] This pull request requires changes to the ROM set
  * [ ] I have opened a roms pull request - https://github.com/86Box/roms/pull/changeme/

References
==========
None.

### CODE REVIEW

File: src/qt/qt_mainwindow.cpp [hunk 1]
```diff
@@ -1646,6 +1652,9 @@ void MainWindow::blitToWidget(int x, int y, int w, int h, int monitor_index)
 
 void MainWindow::keyReleaseEvent(QKeyEvent* event)
 {
+    if (event->key() == Qt::Key_Pause) {
+        plat_pause(dopause ^ 1);
```
Comment (lemondrops) [inline src/qt/qt_mainwindow.cpp:1656]: Wouldn't this prevent the use of the Pause key inside the emulated machine?  
(Although this used to be a problem in the Win32 UI as well...)

Comment (Cacodemon345) [reply src/qt/qt_mainwindow.cpp:1656]: Pause key isn't emulated.

Comment (lemondrops) [reply src/qt/qt_mainwindow.cpp:1656]: What do you mean? It works for me.

Comment (Cacodemon345) [reply src/qt/qt_mainwindow.cpp:1656]: Maybe only on Windows, but not on anything else.

Comment (lemondrops) [reply src/qt/qt_mainwindow.cpp:1656]: Then shouldn't *that* be considered a bug, and fixed?

Comment (Cacodemon345) [reply src/qt/qt_mainwindow.cpp:1656]: More like the pause key should perform only a single function at a time, not both.

Comment (lemondrops) [reply src/qt/qt_mainwindow.cpp:1656]: Then the key to pause the emulator should be (and should have been ever since a long time ago) reassigned to a different key combination.

Comment (Cacodemon345) [reply src/qt/qt_mainwindow.cpp:1656]: We would need to figure out one then.

Comment (Diicorp95) [reply src/qt/qt_mainwindow.cpp:1656]: > Then the key to pause the emulator should be (and should have been ever since a long time ago) reassigned to a different key combination.

This could be an option (switch).

**Review by lemondrops — APPROVED** [review]

File: src/qt/qt_mainwindow.cpp (hunk 1 above)
Comment (OBattler) [reply src/qt/qt_mainwindow.cpp]: I'm going to merge this now because it fixes an open issue. The pause button behavior can be fixed in the future.
