### PR TITLE
qt: Important bug fixes

### LINKED ISSUE #2535: Checkboxes "Сassette", "Tertiary IDE Controller", "Quaternary IDE Controller" are not saved
**Describe the bug**
Starting with build 3388, the "Cassette" checkbox is not saved in 8088 machines. After applying the settings in 8088 machines, if you check the "Cassette" checkbox, then the next time you open the settings window, this checkbox is no longer there.

Starting from build 3501, "Tertiary IDE Controller", "Quaternary IDE Controller" checkboxes are not saved in Slot1 machines. After applying the settings in Slot1 machines (and maybe in some others), if you check the "Tertiary IDE Controller", "Quaternary IDE Controller" checkboxes, then the next time you open the settings window, these checkboxes are gone.

**To Reproduce**
1. Set the checkboxes "Сassette", "Tertiary IDE Controller", "Quaternary IDE Controller" in the corresponding 86Box machines
2. Apply settings
3. Open the settings window again

**Expected behavior**
The checkboxes "Сassette", "Tertiary IDE Controller", "Quaternary IDE Controller" must be saved after applying the settings in the corresponding 86Box machines.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H2
 - 86Box v3.6 x64 Build 3994
 - Build type: regular, old recompiler.

### PR DESCRIPTION
**Pull request by Cacodemon345**
Summary
=======
[qt: Fix hide toggles on resizable main window](https://github.com/86Box/86Box/commit/94c84b299d6b9c58b01bfd07b2d9f6a2be4f04d6)
[qt: Properly display tertiary/quarternary IDE toggle in Settings](https://github.com/86Box/86Box/commit/313b2ab8523beabea87229505ec1abab61c04dbe)
[config: Save and load cassette toggle properly](https://github.com/86Box/86Box/commit/e6cfdf4f6991d4d36d3d2e29ae4cdbb9173cc7d6)

Checklist
=========
* [X] Closes #2535
* [ ] I have discussed this with core contributors already
* [ ] This pull request requires changes to the ROM set
  * [ ] I have opened a roms pull request - https://github.com/86Box/roms/pull/changeme/

References
==========
None.

### CODE REVIEW

File: src/qt/qt_settingsstoragecontrollers.cpp [hunk 1]
```diff
@@ -161,6 +161,8 @@ void SettingsStorageControllers::onCurrentMachineChanged(int machineId) {
     int is_at = IS_AT(machineId);
     ui->checkBoxTertiaryIDE->setEnabled(is_at > 0);
     ui->checkBoxQuaternaryIDE->setEnabled(is_at > 0);
+    ui->checkBoxTertiaryIDE->setChecked(ui->checkBoxTertiaryIDE->isEnabled() && ide_ter_enabled);
+    ui->checkBoxQuaternaryIDE->setChecked(ui->checkBoxQuaternaryIDE->isEnabled() && ide_ter_enabled);
```
Comment (lemondrops) [inline src/qt/qt_settingsstoragecontrollers.cpp:165]:
```suggestion
    ui->checkBoxQuaternaryIDE->setChecked(ui->checkBoxQuaternaryIDE->isEnabled() && ide_qua_enabled);
```

**Review by lemondrops — CHANGES_REQUESTED** [review]

**Review by jriwanek — APPROVED** [review]
